version: '3'
services:
  be:
    image: teamnameis/be:latest
    restart: always
    depends_on:
     - ml
    ports:
     - "1234:1234"
     - "5678:5678"
    networks:
      - backbone
    environment:
      DURATION: 3s
      ROTATE: ROTATE
      ML_PORT: "ml:5000"
  ml:
    image: teamnameis/bone:latest
    restart: always
    ports:
     - "5000:5000"
    networks:
      - backbone

networks:
  backbone:
    driver: bridge
