apiVersion: v1
kind: Service
metadata:
  name: be
spec:
  type: NodePort
  ports:
    - name: be-rest
      protocol: "TCP"
      port: 8080
      targetPort: 1234
      nodePort: 12345
    - name: be-grpc
      protocol: "TCP"
      port: 50000
      targetPort: 5678
      nodePort: 54321
  selector:
    app: be
