apiVersion: v1
kind: Service
metadata:
  name: be
spec:
  type: NodePort
  ports:
    - name: be-rest
      protocol: "TCP"
      port: 8080
      targetPort: 1234
      nodePort: 30000
    - name: be-grpc
      protocol: "TCP"
      port: 8081
      targetPort: 5678
      nodePort: 30001
  selector:
    app: be
